
mybatis.typeAliasesPackage=com.example.yin.model.domain
mybatis.mapperLocations=classpath:mapper/*.xml
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
server.port=8889
#热部署生效
spring.devtools.restart.enabled=false
#设置重启的目录
spring.devtools.restart.additional-paths=src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude=WEB-INF/**
# 关闭CONDITIONS EVALUATION REPORT及自动配置内容向控制台的输出
logging.level.org.springframework.boot.autoconfigure=ERROR
# redis相应的地址  还有一些配置
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.database=0
spring.redis.timeout=1800000
spring.redis.lettuce.pool.max-active=20
spring.redis.lettuce.pool.max-wait=-1
#最大阻塞等待时间(负数表示没限制)
spring.redis.lettuce.pool.max-idle=5
spring.redis.lettuce.pool.min-idle=0
spring.profiles.active=dev
vae.python.path=C:\\Users\\CC\\miniconda3\\envs\\jak_pred\\python.exe
vae.script.path=D:\\Desktop\\backend\\back\\server\\model_files\\vae_predictor.py
vae.timeout.seconds=120

# ?? prediction ???? PredictionService ???
prediction.python.executable=C:\\Users\\CC\\miniconda3\\envs\\jak_pred\\python.exe
prediction.python.script.path=D:\\Desktop\\backend\\back\\server\\model_files\\predict.py

# ===== ??????????? =====
overall.python.executable=C:\\Users\\CC\\miniconda3\\envs\\jak_pred\\python.exe
overall.python.script.path=D:\\Desktop\\backend\\back\\server\\model_files\\all_predict.py
overall.timeout.seconds=60

gnn.python.path=C:\\Users\\CC\\miniconda3\\envs\\jak_pred\\python.exe
gnn.script.path=D:\\Desktop\\backend\\back\\server\\model_files\\gnn_predict.py

# ===== ???????? (TDT) ?? =====
# Python ??????? VAE/GNN ?????
tdt.python.path=C:\\Users\\CC\\miniconda3\\envs\\jak_pred\\python.exe
# ??????????
tdt.script.path=D:\\Desktop\\backend\\back\\server\\model_files\\tradition_predict.py
# ?????????
tdt.timeout.seconds=120

# ===== CNN?? (CNN) ?? =====
# Python ??????? VAE/GNN ?????
cnn.python.path=C:\\Users\\CC\\miniconda3\\envs\\jak_pred\\python.exe
# ??????????
cnn.script.path=D:\\Desktop\\backend\\back\\server\\model_files\\cnn_predict.py
# ?????????
cnn.timeout.seconds=120


